bootstrap.sh: Don't interpolate $LD_LIBRARYN32_PATH
larb0b/irixports pull request #42
Opened 2019-09-19 19:05 UTC by mroach

The caveat message at the end of `bootstrap.sh` interpolates `$LD_LIBRARYN32_PATH` which at least for me resulted in just empty string. It suggested using
`export LD_LIBRARYN32_PATH=:/opt/local/gcc-4.7.4/lib32` While not technically wrong or broken, I don't believe this was the intent.

This change ensures it is output as a string literal.

I also broke up the message onto a couple lines for readability and to make what needs to be done a bit more clear.

New message:

```
When working with irixports, you should make sure that GCC's lib32 directory is in LD_LIBRARYN32_PATH.
In a bourne-like shell, you can put something like this to your profile:

    export LD_LIBRARYN32_PATH=$LD_LIBRARYN32_PATH:/opt/local/gcc-4.7.4/lib32
```

2019-09-19 19:43 UTC, larb0b requested changes
Good catch. It'd probably be better to say something like `into your profile` rather than `to your profile`. I'm also not sure how I feel about the message being broken into multiple lines.

2019-09-19 20:19 UTC, mroach commented
What do you think about keeping the `export` line on its own and the instruction text? I think it makes the extent of the modification (i.e. what you should copy/paste) unambiguous.

I admit I was in an excited hurry to get going and I copied and pasted missing the `export` command entirely. That's where this is coming from /shame

As to the other point. How about "you can add something like this to your profile". Otherwise, I agree `s/to/into`.

2019-09-19 20:23 UTC, mroach commented
Here's another draft as of the last commit:

```
When working with irixports, you should make sure that GCC's lib32 directory is in LD_LIBRARYN32_PATH. In a bourne-like shell, you can add something like this to your profile:

    export LD_LIBRARYN32_PATH=$LD_LIBRARYN32_PATH:/opt/local/gcc-4.7.4/lib32
```

2019-09-19 20:26 UTC, merged

2019-09-19 20:26 UTC, larb0b commented
Thanks!

2019-09-19 20:39 UTC, mroach commented
Thanks for this project! I just got my first SGI machine and this is exactly what I was looking for to get the system in a more convenient state for usage. This is working great :)

2019-09-19 20:50 UTC, larb0b commented
Nice! What machine? :)

IRIX and SGI MIPS machines are really fun in my opinion. I've definitely gotten the most mileage out of them out of all of my retro gear.

2019-09-20 08:52 UTC, mroach commented
I got an O2! I've had my eyes open for a machine at a reasonable price and feel like €120 for an O2 with R10000 was totally reasonable. It hasn't taken me long at all to understand why SGI hardware and IRIX has such an enthusiastic following even to this day. I'm already having a lot more fun than my Sun Blade 1000 which has been a pure pain in the neck.

Thanks for the Discord tip! I'll hop on soon.

2019-09-21 03:56 UTC, larb0b commented
Wow, nice deal!

I like Sun machines but I've gotten way less mileage out of them than I've gotten out of my SGI machines.

We'll be glad to have you. :)